### ISSUE TITLE
JSON parsing problem

### ISSUE THREAD

**Issue by ghost** [SquidKit/SquidKit#1]
My project intends to adopt SquidKit, but two problems, hope to provide support: 
## First

JSONEntity should be allowed to initialise a null values, so that I can be declared a global variables as UITabelView's datasource 

Like this: 

``` swift
public init () { 
    self.entity = Entity("", NilValue())
} 
```
## Second

Most of the time, API will not only return a dictionary, and returns an array, such as 

[link to Github's public Gists API ](https://api.github.com/gists/public)

So I hope to provide support for arrays

``` swift
public init(jsonArray:NSArray) {
    self.entity = Entity("", jsonArray)
}
```

**Comment by mleavy** [comment]
Thanks for the suggestions. I've added the requested functionality. I've also updated `init(resourceFilename:String)` to handle array structures as well as dictionaries.

**Comment by ghost** [comment]
Thanks
